assets:
  settings.xml: yegor256/home#assets/artipie/settings.xml
  pubring.gpg: yegor256/home#assets/pubring.gpg
  secring.gpg: yegor256/home#assets/secring.gpg
env:
  MAVEN_OPTS: -XX:MaxPermSize=256m -Xmx1g
  JAVA_OPTS: -XX:MaxPermSize=256m -Xmx1g
architects:
  - yegor256
  - g4s8
install: |
  sudo locale-gen en_US en_US.UTF-8
  sudo dpkg-reconfigure locales
  export LC_ALL=en_US.UTF-8
  export LANG=en_US.UTF-8
  export LANGUAGE=en_US.UTF-8
  sudo gem install pdd
  sudo gem install xcop
release:
  script: |-
    pdd -f /dev/null
    mvn versions:set "-DnewVersion=${tag}"
    git commit -am "${tag}"
    mvn clean deploy -Partipie,sonatype,qulice --errors --settings ../settings.xml
merge:
  script: |
    echo We don't merge via rultor
    exit 1
deploy:
  script: |
    echo There is nothing to deploy
    exit 1
